server.port=8081
jwt.secret=YourSuperSecretKeyThatIsAtLeast256BitsLong1234567890
jwt.expiration=86400000
spring.application.name=auth-service

# CORS — allow Angular dev server
cors.allowed-origins=http://localhost:4200

# Supabase Configuration
supabase.url=https://yytgzdqkautnpfqxfomj.supabase.co
supabase.api-key=sb_publishable_ZeXbsrLCcGDZzXziWFdaFw_wlXGcWzk
