server.port=${PORT:8081}
jwt.secret=${JWT_SECRET:YourSuperSecretKeyThatIsAtLeast256BitsLong1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}
spring.application.name=auth-service

# CORS — allow Angular dev server
cors.allowed-origins=http://localhost:4200

# Supabase Configuration
supabase.url=${SUPABASE_URL:https://yytgzdqkautnpfqxfomj.supabase.co}
supabase.api-key=${SUPABASE_API_KEY:sb_publishable_ZeXbsrLCcGDZzXziWFdaFw_wlXGcWzk}
